In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data/seq-meta.csv')
df

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,MH481285.1,04-MAR-2019,Phytophthora niederhauseri isolate TARI 206231...,"Lin,C.P., Tsai,J.N. and Ann,P.J.",AAAAGAGAAGGTGTTTTTTATGGACAATGTAGTGAAATTTGTGGAG...,462,Phytophthora niederhauseri,2651253,<0,144,1.0
1,MK173058.1,18-FEB-2019,Peronospora variabilis isolate Kari cytochrome...,"Rollano-Penaloza,O.M.",GTATTATTAACTTTCATCATGATTTGATGTTTTTTTTAATTATTGT...,544,Peronospora variabilis,162102,<0,>544,1.0
2,MG788317.1,10-FEB-2019,Phytopythium sp. voucher Chen 218 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
3,MG788316.1,10-FEB-2019,Phytopythium sp. voucher Chen 216 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
4,MG788315.1,10-FEB-2019,Phytopythium sp. voucher Chen 172 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
...,...,...,...,...,...,...,...,...,...,...,...
6939,ON286950.1,14-SEP-2022,Globisporangium spinosum cytochrome c oxidase ...,"Hossain,M.D., Akter,A. and Wick,R.L.",CGATTTAATGTTTTTTTTAATTGTTGTAACTATTTTTGTTTGTTGG...,512,Globisporangium spinosum,2125998,<0,>512,1.0
6940,ON532704.1,13-SEP-2022,Albugo candida strain LemidPRAru20 cytochrome ...,"Zielinski,E.C., Claus,A., Hahn,M.H., Koch,G. a...",AAGATCCAGCTACTCCTGTTATGGAAGGTATTATTAATTTTCATCA...,519,Albugo candida,65357,<0,>519,1.0
6941,OK631964.1,05-SEP-2022,Plasmopara muralis isolate Pm2 cytochrome oxid...,"Salgado-Salazar,C.",CAAGATCCAGCAACCCCGGTTATGGAAGGTATTATTAACTTTCATC...,553,Plasmopara muralis,1196443,<0,>553,1.0
6942,OK631963.1,05-SEP-2022,Plasmopara sp. isolate U5 cytochrome oxidase s...,"Salgado-Salazar,C.",GGTTTTCAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACT...,611,Plasmopara sp.,2811085,<0,>611,1.0
6943,OK631962.1,05-SEP-2022,Plasmopara sp. isolate U4 cytochrome oxidase s...,"Salgado-Salazar,C.",GGTTTTCAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACT...,611,Plasmopara sp.,2811085,<0,>611,1.0

In [4]:
filtered = df.drop(df[df['title'].str.lower().str.startswith('unverified')].index)
filtered

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,MH481285.1,04-MAR-2019,Phytophthora niederhauseri isolate TARI 206231...,"Lin,C.P., Tsai,J.N. and Ann,P.J.",AAAAGAGAAGGTGTTTTTTATGGACAATGTAGTGAAATTTGTGGAG...,462,Phytophthora niederhauseri,2651253,<0,144,1.0
1,MK173058.1,18-FEB-2019,Peronospora variabilis isolate Kari cytochrome...,"Rollano-Penaloza,O.M.",GTATTATTAACTTTCATCATGATTTGATGTTTTTTTTAATTATTGT...,544,Peronospora variabilis,162102,<0,>544,1.0
2,MG788317.1,10-FEB-2019,Phytopythium sp. voucher Chen 218 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
3,MG788316.1,10-FEB-2019,Phytopythium sp. voucher Chen 216 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
4,MG788315.1,10-FEB-2019,Phytopythium sp. voucher Chen 172 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
...,...,...,...,...,...,...,...,...,...,...,...
6939,ON286950.1,14-SEP-2022,Globisporangium spinosum cytochrome c oxidase ...,"Hossain,M.D., Akter,A. and Wick,R.L.",CGATTTAATGTTTTTTTTAATTGTTGTAACTATTTTTGTTTGTTGG...,512,Globisporangium spinosum,2125998,<0,>512,1.0
6940,ON532704.1,13-SEP-2022,Albugo candida strain LemidPRAru20 cytochrome ...,"Zielinski,E.C., Claus,A., Hahn,M.H., Koch,G. a...",AAGATCCAGCTACTCCTGTTATGGAAGGTATTATTAATTTTCATCA...,519,Albugo candida,65357,<0,>519,1.0
6941,OK631964.1,05-SEP-2022,Plasmopara muralis isolate Pm2 cytochrome oxid...,"Salgado-Salazar,C.",CAAGATCCAGCAACCCCGGTTATGGAAGGTATTATTAACTTTCATC...,553,Plasmopara muralis,1196443,<0,>553,1.0
6942,OK631963.1,05-SEP-2022,Plasmopara sp. isolate U5 cytochrome oxidase s...,"Salgado-Salazar,C.",GGTTTTCAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACT...,611,Plasmopara sp.,2811085,<0,>611,1.0
6943,OK631962.1,05-SEP-2022,Plasmopara sp. isolate U4 cytochrome oxidase s...,"Salgado-Salazar,C.",GGTTTTCAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACT...,611,Plasmopara sp.,2811085,<0,>611,1.0

### Remove sequences with unknown COX2 region

In [5]:
filtered = filtered.drop(df[(df['cox2_start'].isna()) | (df['cox2_start'].isna())].index)
filtered

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,MH481285.1,04-MAR-2019,Phytophthora niederhauseri isolate TARI 206231...,"Lin,C.P., Tsai,J.N. and Ann,P.J.",AAAAGAGAAGGTGTTTTTTATGGACAATGTAGTGAAATTTGTGGAG...,462,Phytophthora niederhauseri,2651253,<0,144,1.0
1,MK173058.1,18-FEB-2019,Peronospora variabilis isolate Kari cytochrome...,"Rollano-Penaloza,O.M.",GTATTATTAACTTTCATCATGATTTGATGTTTTTTTTAATTATTGT...,544,Peronospora variabilis,162102,<0,>544,1.0
2,MG788317.1,10-FEB-2019,Phytopythium sp. voucher Chen 218 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
3,MG788316.1,10-FEB-2019,Phytopythium sp. voucher Chen 216 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
4,MG788315.1,10-FEB-2019,Phytopythium sp. voucher Chen 172 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
...,...,...,...,...,...,...,...,...,...,...,...
6939,ON286950.1,14-SEP-2022,Globisporangium spinosum cytochrome c oxidase ...,"Hossain,M.D., Akter,A. and Wick,R.L.",CGATTTAATGTTTTTTTTAATTGTTGTAACTATTTTTGTTTGTTGG...,512,Globisporangium spinosum,2125998,<0,>512,1.0
6940,ON532704.1,13-SEP-2022,Albugo candida strain LemidPRAru20 cytochrome ...,"Zielinski,E.C., Claus,A., Hahn,M.H., Koch,G. a...",AAGATCCAGCTACTCCTGTTATGGAAGGTATTATTAATTTTCATCA...,519,Albugo candida,65357,<0,>519,1.0
6941,OK631964.1,05-SEP-2022,Plasmopara muralis isolate Pm2 cytochrome oxid...,"Salgado-Salazar,C.",CAAGATCCAGCAACCCCGGTTATGGAAGGTATTATTAACTTTCATC...,553,Plasmopara muralis,1196443,<0,>553,1.0
6942,OK631963.1,05-SEP-2022,Plasmopara sp. isolate U5 cytochrome oxidase s...,"Salgado-Salazar,C.",GGTTTTCAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACT...,611,Plasmopara sp.,2811085,<0,>611,1.0
6943,OK631962.1,05-SEP-2022,Plasmopara sp. isolate U4 cytochrome oxidase s...,"Salgado-Salazar,C.",GGTTTTCAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACT...,611,Plasmopara sp.,2811085,<0,>611,1.0

### Trim sequences to COX2 region

In [6]:
from Bio import SeqIO

In [7]:
def trim_seq(cox2_start: str, cox2_end: str, seq: str) -> str:
    start = int(str(cox2_start).lstrip('<'))
    end = int(str(cox2_end).lstrip('>'))
    assert(start < end)
    return seq[start:end]

In [8]:
filtered['sequence'] = filtered.apply(lambda row: trim_seq(row['cox2_start'], row['cox2_end'], row['sequence']), axis=1)
filtered

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,MH481285.1,04-MAR-2019,Phytophthora niederhauseri isolate TARI 206231...,"Lin,C.P., Tsai,J.N. and Ann,P.J.",AAAAGAGAAGGTGTTTTTTATGGACAATGTAGTGAAATTTGTGGAG...,462,Phytophthora niederhauseri,2651253,<0,144,1.0
1,MK173058.1,18-FEB-2019,Peronospora variabilis isolate Kari cytochrome...,"Rollano-Penaloza,O.M.",GTATTATTAACTTTCATCATGATTTGATGTTTTTTTTAATTATTGT...,544,Peronospora variabilis,162102,<0,>544,1.0
2,MG788317.1,10-FEB-2019,Phytopythium sp. voucher Chen 218 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
3,MG788316.1,10-FEB-2019,Phytopythium sp. voucher Chen 216 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
4,MG788315.1,10-FEB-2019,Phytopythium sp. voucher Chen 172 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
...,...,...,...,...,...,...,...,...,...,...,...
6939,ON286950.1,14-SEP-2022,Globisporangium spinosum cytochrome c oxidase ...,"Hossain,M.D., Akter,A. and Wick,R.L.",CGATTTAATGTTTTTTTTAATTGTTGTAACTATTTTTGTTTGTTGG...,512,Globisporangium spinosum,2125998,<0,>512,1.0
6940,ON532704.1,13-SEP-2022,Albugo candida strain LemidPRAru20 cytochrome ...,"Zielinski,E.C., Claus,A., Hahn,M.H., Koch,G. a...",AAGATCCAGCTACTCCTGTTATGGAAGGTATTATTAATTTTCATCA...,519,Albugo candida,65357,<0,>519,1.0
6941,OK631964.1,05-SEP-2022,Plasmopara muralis isolate Pm2 cytochrome oxid...,"Salgado-Salazar,C.",CAAGATCCAGCAACCCCGGTTATGGAAGGTATTATTAACTTTCATC...,553,Plasmopara muralis,1196443,<0,>553,1.0
6942,OK631963.1,05-SEP-2022,Plasmopara sp. isolate U5 cytochrome oxidase s...,"Salgado-Salazar,C.",GGTTTTCAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACT...,611,Plasmopara sp.,2811085,<0,>611,1.0
6943,OK631962.1,05-SEP-2022,Plasmopara sp. isolate U4 cytochrome oxidase s...,"Salgado-Salazar,C.",GGTTTTCAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACT...,611,Plasmopara sp.,2811085,<0,>611,1.0

### Remove short (<200bp) sequences

In [9]:
trimmed = filtered[filtered['sequence'].str.len() >= 200]
trimmed

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
1,MK173058.1,18-FEB-2019,Peronospora variabilis isolate Kari cytochrome...,"Rollano-Penaloza,O.M.",GTATTATTAACTTTCATCATGATTTGATGTTTTTTTTAATTATTGT...,544,Peronospora variabilis,162102,<0,>544,1.0
2,MG788317.1,10-FEB-2019,Phytopythium sp. voucher Chen 218 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
3,MG788316.1,10-FEB-2019,Phytopythium sp. voucher Chen 216 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
4,MG788315.1,10-FEB-2019,Phytopythium sp. voucher Chen 172 cytochrome c...,"Chen,J.J.",GGTATTATAAATTTTTATCATGACATAATGTTTTTTTTAGTTATTA...,528,Phytopythium sp.,1897510,<0,>528,1.0
5,MH234579.1,02-FEB-2019,Albugo candida isolate G725 cytochrome oxidase...,"Latinovic,J., Latinovic,N., Jakse,J. and Radis...",GCAAAATGGGTTTTCAAGATCCAGCTACTCCTGTTATGGAAGGTAT...,632,Albugo candida,65357,<0,>632,1.0
...,...,...,...,...,...,...,...,...,...,...,...
6939,ON286950.1,14-SEP-2022,Globisporangium spinosum cytochrome c oxidase ...,"Hossain,M.D., Akter,A. and Wick,R.L.",CGATTTAATGTTTTTTTTAATTGTTGTAACTATTTTTGTTTGTTGG...,512,Globisporangium spinosum,2125998,<0,>512,1.0
6940,ON532704.1,13-SEP-2022,Albugo candida strain LemidPRAru20 cytochrome ...,"Zielinski,E.C., Claus,A., Hahn,M.H., Koch,G. a...",AAGATCCAGCTACTCCTGTTATGGAAGGTATTATTAATTTTCATCA...,519,Albugo candida,65357,<0,>519,1.0
6941,OK631964.1,05-SEP-2022,Plasmopara muralis isolate Pm2 cytochrome oxid...,"Salgado-Salazar,C.",CAAGATCCAGCAACCCCGGTTATGGAAGGTATTATTAACTTTCATC...,553,Plasmopara muralis,1196443,<0,>553,1.0
6942,OK631963.1,05-SEP-2022,Plasmopara sp. isolate U5 cytochrome oxidase s...,"Salgado-Salazar,C.",GGTTTTCAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACT...,611,Plasmopara sp.,2811085,<0,>611,1.0
6943,OK631962.1,05-SEP-2022,Plasmopara sp. isolate U4 cytochrome oxidase s...,"Salgado-Salazar,C.",GGTTTTCAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACT...,611,Plasmopara sp.,2811085,<0,>611,1.0

### Remove Sequences with unknown species (i.e. 'sp.')

In [10]:
trimmed = trimmed[~trimmed['organism_name'].str.contains('sp.', case=False, regex=False)]
trimmed

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
1,MK173058.1,18-FEB-2019,Peronospora variabilis isolate Kari cytochrome...,"Rollano-Penaloza,O.M.",GTATTATTAACTTTCATCATGATTTGATGTTTTTTTTAATTATTGT...,544,Peronospora variabilis,162102,<0,>544,1.0
5,MH234579.1,02-FEB-2019,Albugo candida isolate G725 cytochrome oxidase...,"Latinovic,J., Latinovic,N., Jakse,J. and Radis...",GCAAAATGGGTTTTCAAGATCCAGCTACTCCTGTTATGGAAGGTAT...,632,Albugo candida,65357,<0,>632,1.0
7,MH665652.1,27-JAN-2019,Bremia itoana cytochrome c oxidase subunit II ...,"Choi,Y.J., Park,J.H., Lee,J. and Shin,H.D.",GCAACACCTGTAATGGAAGGTATCATTAATTTTCATCATGATATTA...,584,Bremia itoana,2507514,<0,>584,1.0
8,KY412456.1,10-JAN-2019,Pustula xinyuanensis voucher HMUT 3476 cytochr...,"Xu,B., Choi,Y.J., Song,J.G., Xi,P.G., Li,M.H.,...",GTAATGGAAGGAATTATAAACTTTCATCATGATTTAATGTTTTTTT...,578,Pustula xinyuanensis,2069635,<0,>578,1.0
9,KY412455.1,10-JAN-2019,Pustula xinyuanensis voucher HMUT 3473 cytochr...,"Xu,B., Choi,Y.J., Song,J.G., Xi,P.G., Li,M.H.,...",GTAATGGAAGGAATTATAAACTTTCATCATGATTTAATGTTTTTTT...,561,Pustula xinyuanensis,2069635,<0,>561,1.0
...,...,...,...,...,...,...,...,...,...,...,...
6937,OK574284.1,28-SEP-2022,Phytophthora cactorum voucher 262HNP mitochond...,"Li,M. and Lin,T.",ATGATAATAACAAATTATATAAATAACCAATTCACTTTTTTAGATA...,38014,Phytophthora cactorum,29920,37042,37819,1.0
6938,OK555490.1,28-SEP-2022,Phytophthora cactorum voucher CH98PA11 mitocho...,"Li,M. and Lin,T.",ATGATAATAACAAATTATATAAATAACCAATTCACTTTTTTAGATA...,38016,Phytophthora cactorum,29920,37044,37821,1.0
6939,ON286950.1,14-SEP-2022,Globisporangium spinosum cytochrome c oxidase ...,"Hossain,M.D., Akter,A. and Wick,R.L.",CGATTTAATGTTTTTTTTAATTGTTGTAACTATTTTTGTTTGTTGG...,512,Globisporangium spinosum,2125998,<0,>512,1.0
6940,ON532704.1,13-SEP-2022,Albugo candida strain LemidPRAru20 cytochrome ...,"Zielinski,E.C., Claus,A., Hahn,M.H., Koch,G. a...",AAGATCCAGCTACTCCTGTTATGGAAGGTATTATTAATTTTCATCA...,519,Albugo candida,65357,<0,>519,1.0
6941,OK631964.1,05-SEP-2022,Plasmopara muralis isolate Pm2 cytochrome oxid...,"Salgado-Salazar,C.",CAAGATCCAGCAACCCCGGTTATGGAAGGTATTATTAACTTTCATC...,553,Plasmopara muralis,1196443,<0,>553,1.0

### Remove sequences from uncultured samples

In [11]:
trimmed[trimmed['organism_name'].str.contains('uncultured', case=False)]

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
17,MG787100.1,10-DEC-2018,Uncultured Oomycota isolate Ect6Para cytochrom...,"Garvetto,A., Nezan,E., Badis,Y., Bilien,G., Ar...",GGTCGTACGTTGTGTTTATTTTTTTAATCAAACCGTTCATCCGCAA...,471,uncultured Oomycota,179533,<0,>471,1.0
19,MF960909.1,04-DEC-2018,Uncultured Oomycota isolate Melo1Para cytochro...,"Garvetto,A., Nezan,E., Badis,Y., Bilien,G., Ar...",TTAACATAATGTTTTTTTTAATCGTGATTGTGGTCTTTACCTCGTG...,576,uncultured Oomycota,179533,<0,>576,1.0

In [12]:
trimmed = trimmed[~trimmed['organism_name'].str.contains('uncultured', case=False)]
trimmed

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
1,MK173058.1,18-FEB-2019,Peronospora variabilis isolate Kari cytochrome...,"Rollano-Penaloza,O.M.",GTATTATTAACTTTCATCATGATTTGATGTTTTTTTTAATTATTGT...,544,Peronospora variabilis,162102,<0,>544,1.0
5,MH234579.1,02-FEB-2019,Albugo candida isolate G725 cytochrome oxidase...,"Latinovic,J., Latinovic,N., Jakse,J. and Radis...",GCAAAATGGGTTTTCAAGATCCAGCTACTCCTGTTATGGAAGGTAT...,632,Albugo candida,65357,<0,>632,1.0
7,MH665652.1,27-JAN-2019,Bremia itoana cytochrome c oxidase subunit II ...,"Choi,Y.J., Park,J.H., Lee,J. and Shin,H.D.",GCAACACCTGTAATGGAAGGTATCATTAATTTTCATCATGATATTA...,584,Bremia itoana,2507514,<0,>584,1.0
8,KY412456.1,10-JAN-2019,Pustula xinyuanensis voucher HMUT 3476 cytochr...,"Xu,B., Choi,Y.J., Song,J.G., Xi,P.G., Li,M.H.,...",GTAATGGAAGGAATTATAAACTTTCATCATGATTTAATGTTTTTTT...,578,Pustula xinyuanensis,2069635,<0,>578,1.0
9,KY412455.1,10-JAN-2019,Pustula xinyuanensis voucher HMUT 3473 cytochr...,"Xu,B., Choi,Y.J., Song,J.G., Xi,P.G., Li,M.H.,...",GTAATGGAAGGAATTATAAACTTTCATCATGATTTAATGTTTTTTT...,561,Pustula xinyuanensis,2069635,<0,>561,1.0
...,...,...,...,...,...,...,...,...,...,...,...
6937,OK574284.1,28-SEP-2022,Phytophthora cactorum voucher 262HNP mitochond...,"Li,M. and Lin,T.",ATGATAATAACAAATTATATAAATAACCAATTCACTTTTTTAGATA...,38014,Phytophthora cactorum,29920,37042,37819,1.0
6938,OK555490.1,28-SEP-2022,Phytophthora cactorum voucher CH98PA11 mitocho...,"Li,M. and Lin,T.",ATGATAATAACAAATTATATAAATAACCAATTCACTTTTTTAGATA...,38016,Phytophthora cactorum,29920,37044,37821,1.0
6939,ON286950.1,14-SEP-2022,Globisporangium spinosum cytochrome c oxidase ...,"Hossain,M.D., Akter,A. and Wick,R.L.",CGATTTAATGTTTTTTTTAATTGTTGTAACTATTTTTGTTTGTTGG...,512,Globisporangium spinosum,2125998,<0,>512,1.0
6940,ON532704.1,13-SEP-2022,Albugo candida strain LemidPRAru20 cytochrome ...,"Zielinski,E.C., Claus,A., Hahn,M.H., Koch,G. a...",AAGATCCAGCTACTCCTGTTATGGAAGGTATTATTAATTTTCATCA...,519,Albugo candida,65357,<0,>519,1.0
6941,OK631964.1,05-SEP-2022,Plasmopara muralis isolate Pm2 cytochrome oxid...,"Salgado-Salazar,C.",CAAGATCCAGCAACCCCGGTTATGGAAGGTATTATTAACTTTCATC...,553,Plasmopara muralis,1196443,<0,>553,1.0

### Remove (nom. inval.) species

In [13]:
trimmed = trimmed[~trimmed['title'].str.contains('nom. inval.', case=False, regex=False)]
trimmed = trimmed[~trimmed['organism_name'].str.contains('nom. inval.', case=False, regex=False)]

In [14]:
trimmed.value_counts('tax_id')

tax_id
4792       219
65357      196
143453     190
283009     149
4787       139
          ...
758760       1
795340       1
880412       1
1087854      1
1087859      1
Name: count, Length: 762, dtype: int64

In [15]:
trimmed.to_csv('data/cox2-db-filtered.csv', sep='\t', index=False)

In [16]:
with open('data/cox2-db-filtered.fa', 'w') as out:
    for index, row in trimmed.iterrows():
        print(f'>{row["accession"]}', file=out)
        print(row['sequence'], file=out)

#### cluster with vsearch

```bash
vsearch --cluster_fast data/cox2-db-filtered.fa -id 1.0 --strand both --msaout data/clust-msa.fa --clusterout_id --uc data/clust-results.tsv
```