In [83]:
import pandas as pd

In [84]:
df = pd.read_csv('data/seq-meta.csv')
df

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,JF414552.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-274 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
1,JF414551.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-273 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
2,JF414550.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-272 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
3,JF414549.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-269 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
4,JF414548.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-268 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
...,...,...,...,...,...,...,...,...,...,...,...
8507,OR094655.1,28-AUG-2023,Peronospora belbahrii isolate p15-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,564,Peronospora belbahrii,622444,<0,>564,1.0
8508,OR094654.1,28-AUG-2023,Peronospora belbahrii isolate p14-1-1 cytochro...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,600,Peronospora belbahrii,622444,<0,>600,1.0
8509,OR094653.1,28-AUG-2023,Peronospora belbahrii isolate p13-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",CAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACC...,564,Peronospora belbahrii,622444,<0,>564,1.0
8510,OR094652.1,28-AUG-2023,Peronospora belbahrii isolate p12-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,601,Peronospora belbahrii,622444,<0,>601,1.0
8511,OR094651.1,28-AUG-2023,Peronospora belbahrii isolate p11-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",TTATGGAAGGTATTATTAACTTTCACCATGATTTAATGTTTTTTTT...,541,Peronospora belbahrii,622444,<0,>541,1.0

In [85]:
filtered = df.drop(df[df['title'].str.lower().str.startswith('unverified')].index)
filtered

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,JF414552.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-274 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
1,JF414551.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-273 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
2,JF414550.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-272 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
3,JF414549.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-269 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
4,JF414548.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-268 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
...,...,...,...,...,...,...,...,...,...,...,...
8507,OR094655.1,28-AUG-2023,Peronospora belbahrii isolate p15-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,564,Peronospora belbahrii,622444,<0,>564,1.0
8508,OR094654.1,28-AUG-2023,Peronospora belbahrii isolate p14-1-1 cytochro...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,600,Peronospora belbahrii,622444,<0,>600,1.0
8509,OR094653.1,28-AUG-2023,Peronospora belbahrii isolate p13-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",CAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACC...,564,Peronospora belbahrii,622444,<0,>564,1.0
8510,OR094652.1,28-AUG-2023,Peronospora belbahrii isolate p12-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,601,Peronospora belbahrii,622444,<0,>601,1.0
8511,OR094651.1,28-AUG-2023,Peronospora belbahrii isolate p11-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",TTATGGAAGGTATTATTAACTTTCACCATGATTTAATGTTTTTTTT...,541,Peronospora belbahrii,622444,<0,>541,1.0

In [86]:
filtered = filtered.dropna(subset=['cox2_start', 'cox2_end'])
filtered

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,JF414552.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-274 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
1,JF414551.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-273 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
2,JF414550.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-272 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
3,JF414549.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-269 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
4,JF414548.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-268 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
...,...,...,...,...,...,...,...,...,...,...,...
8507,OR094655.1,28-AUG-2023,Peronospora belbahrii isolate p15-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,564,Peronospora belbahrii,622444,<0,>564,1.0
8508,OR094654.1,28-AUG-2023,Peronospora belbahrii isolate p14-1-1 cytochro...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,600,Peronospora belbahrii,622444,<0,>600,1.0
8509,OR094653.1,28-AUG-2023,Peronospora belbahrii isolate p13-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",CAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACC...,564,Peronospora belbahrii,622444,<0,>564,1.0
8510,OR094652.1,28-AUG-2023,Peronospora belbahrii isolate p12-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,601,Peronospora belbahrii,622444,<0,>601,1.0
8511,OR094651.1,28-AUG-2023,Peronospora belbahrii isolate p11-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",TTATGGAAGGTATTATTAACTTTCACCATGATTTAATGTTTTTTTT...,541,Peronospora belbahrii,622444,<0,>541,1.0

### Remove sequences with unknown COX2 region

In [87]:
filtered = filtered.drop(filtered[(filtered['cox2_start'].isna()) | (filtered['cox2_start'].isna())].index)
filtered

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,JF414552.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-274 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
1,JF414551.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-273 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
2,JF414550.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-272 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
3,JF414549.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-269 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
4,JF414548.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-268 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
...,...,...,...,...,...,...,...,...,...,...,...
8507,OR094655.1,28-AUG-2023,Peronospora belbahrii isolate p15-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,564,Peronospora belbahrii,622444,<0,>564,1.0
8508,OR094654.1,28-AUG-2023,Peronospora belbahrii isolate p14-1-1 cytochro...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,600,Peronospora belbahrii,622444,<0,>600,1.0
8509,OR094653.1,28-AUG-2023,Peronospora belbahrii isolate p13-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",CAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACC...,564,Peronospora belbahrii,622444,<0,>564,1.0
8510,OR094652.1,28-AUG-2023,Peronospora belbahrii isolate p12-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,601,Peronospora belbahrii,622444,<0,>601,1.0
8511,OR094651.1,28-AUG-2023,Peronospora belbahrii isolate p11-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",TTATGGAAGGTATTATTAACTTTCACCATGATTTAATGTTTTTTTT...,541,Peronospora belbahrii,622444,<0,>541,1.0

In [88]:
full_cox2_start = filtered[(filtered['cox2_start'] != '<0') & (filtered['cox2_start'] != '0')]
full_cox2_start[full_cox2_start['sequence'].str.startswith('ATG')]#.value_counts(subset='organism_name')

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
1562,OQ735416.1,09-MAY-2023,Phytophthora sp. ML-2023a voucher AM18FRL12 mi...,"Li,M. and Wang,H.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39675,Phytophthora sp. ML-2023a,3044284,38692,39469,1.0
1641,NC_067069.1,15-APR-2023,Phytophthora asparagi voucher CBS132095 mitoch...,"Li,M. and Lin,T.",ATGAATTTTAAAAATATAAATAAATGGTCAACAAGGTGGCTTTTTT...,42741,Phytophthora asparagi,631358,41747,42524,1.0
1642,NC_067068.1,15-APR-2023,Phytophthora capensis voucher CBS128319 mitoch...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,37845,Phytophthora capensis,911891,36848,37625,1.0
1648,NC_067067.1,14-APR-2023,Phytophthora hedraiandra voucher CBS111725 mit...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAACAAATGGGCAACAAGATGGCTTTTTT...,38349,Phytophthora hedraiandra,295481,37371,38148,1.0
1651,NC_067071.1,13-APR-2023,Phytophthora humicola voucher P3826 mitochondr...,"Li,M. and Lin,T.",ATGAATTTTAAAAATATAAATAAATGGTCAACTAGATGGCTTTTTT...,37201,Phytophthora humicola,129352,36193,36970,1.0
1652,NC_067065.1,13-APR-2023,Phytophthora botryosa voucher CBS581_69 mitoch...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39743,Phytophthora botryosa,129348,38740,39517,1.0
1658,NC_067075.1,12-APR-2023,Phytophthora pseudotsugae voucher P10339 mitoc...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGGCAACAAGATGGCTTTTTT...,37895,Phytophthora pseudotsugae,53987,36924,37701,1.0
1659,NC_067074.1,12-APR-2023,Phytophthora gonapodyides voucher P7050 mitoch...,"Li,M. and Lin,T.",ATGAATTTTAAAAATATAAATAAATGGTCAACTCGATGGCTTTTTT...,44132,Phytophthora gonapodyides,78237,43120,43897,1.0
1660,NC_067073.1,12-APR-2023,Phytophthora clandestina voucher P3942 mitocho...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTTAACAAGATGGCTTTTTT...,40293,Phytophthora clandestina,89334,39318,40095,1.0
1661,NC_067072.1,12-APR-2023,Phytophthora ilicis voucher P3939 mitochondrio...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,38392,Phytophthora ilicis,89335,37397,38168,1.0
1662,NC_067070.1,12-APR-2023,Phytophthora citricola voucher P0713 mitochond...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,38341,Phytophthora citricola,53984,37341,38118,1.0
1668,NC_067066.1,11-APR-2023,Phytophthora citrophthora voucher CBS950_87 mi...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,37510,Phytophthora citrophthora,4793,36510,37287,1.0
1705,NC_005984.1,03-APR-2023,"Saprolegnia ferax mitochondrion, complete genome","Grayburn,W.S., Hudspeth,D.S., Gane,M.K. and Hu...",ATGATACCTATTATTATAAATGGTGTAAAAATGCATGTAAAAAAAA...,46930,Saprolegnia ferax,4770,31826,32585,1.0
1881,OK574305.1,28-SEP-2022,Phytophthora capsici voucher Pc389 mitochondri...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,37187,Phytophthora capsici,4784,36186,36963,1.0
1882,OK574304.1,28-SEP-2022,Phytophthora pseudotsugae voucher P10339 mitoc...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGGCAACAAGATGGCTTTTTT...,37895,Phytophthora pseudotsugae,53987,36924,37701,1.0
1883,OK574303.1,28-SEP-2022,Phytophthora gonapodyides voucher P7050 mitoch...,"Li,M. and Lin,T.",ATGAATTTTAAAAATATAAATAAATGGTCAACTCGATGGCTTTTTT...,44132,Phytophthora gonapodyides,78237,43120,43897,1.0
1884,OK574302.1,28-SEP-2022,Phytophthora clandestina voucher P3942 mitocho...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTTAACAAGATGGCTTTTTT...,40293,Phytophthora clandestina,89334,39318,40095,1.0
1885,OK574301.1,28-SEP-2022,Phytophthora ilicis voucher P3939 mitochondrio...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,38392,Phytophthora ilicis,89335,37397,38168,1.0
1886,OK574300.1,28-SEP-2022,Phytophthora humicola voucher P3826 mitochondr...,"Li,M. and Lin,T.",ATGAATTTTAAAAATATAAATAAATGGTCAACTAGATGGCTTTTTT...,37201,Phytophthora humicola,129352,36193,36970,1.0
1887,OK574299.1,28-SEP-2022,Phytophthora citricola voucher P0713 mitochond...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,38341,Phytophthora citricola,53984,37341,38118,1.0
1888,OK574298.1,28-SEP-2022,Phytophthora kernoviae voucher NZFS3630 mitoch...,"Li,M. and Lin,T.",ATGAATTTTAAAAATATAAATAAATGGGCAACTAGATGGCTTTTTT...,37482,Phytophthora kernoviae,325452,36487,37264,1.0
1889,OK574297.1,28-SEP-2022,Phytophthora pluvialis voucher NZFS3000 mitoch...,"Li,M. and Lin,T.",ATGTATTTTCAAAAAATAAATAAATGGTCAACAAGATGGCTTTTTT...,39327,Phytophthora pluvialis,1330343,38331,39102,1.0
1890,OK574296.1,28-SEP-2022,Phytophthora colocasiae voucher Fj20_1 mitocho...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,41838,Phytophthora colocasiae,129350,40835,41612,1.0
1891,OK574295.1,28-SEP-2022,Phytophthora cactorum voucher CH9812411 mitoch...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGGCAACAAGATGGCTTTTTT...,38016,Phytophthora cactorum,29920,37044,37821,1.0
1892,OK574294.1,28-SEP-2022,Phytophthora cactorum voucher CH98LOQ1 mitocho...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGGCAACAAGATGGCTTTTTT...,38114,Phytophthora cactorum,29920,37145,37922,1.0
1893,OK574293.1,28-SEP-2022,Phytophthora cactorum voucher CH02MKPy001 mito...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGGCAACAAGATGGCTTTTTT...,38091,Phytophthora cactorum,29920,37119,37896,1.0
1894,OK574292.1,28-SEP-2022,Phytophthora asparagi voucher CBS132095 mitoch...,"Li,M. and Lin,T.",ATGAATTTTAAAAATATAAATAAATGGTCAACAAGGTGGCTTTTTT...,42741,Phytophthora asparagi,631358,41747,42524,1.0
1895,OK574291.1,28-SEP-2022,Phytophthora capensis voucher CBS128319 mitoch...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,37845,Phytophthora capensis,911891,36848,37625,1.0
1896,OK574290.1,28-SEP-2022,Phytophthora hedraiandra voucher CBS111725 mit...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAACAAATGGGCAACAAGATGGCTTTTTT...,38349,Phytophthora hedraiandra,295481,37371,38148,1.0
1897,OK574289.1,28-SEP-2022,Phytophthora citrophthora voucher CBS950_87 mi...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,37510,Phytophthora citrophthora,4793,36510,37287,1.0
1898,OK574288.1,28-SEP-2022,Phytophthora botryosa voucher CBS581_69 mitoch...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39743,Phytophthora botryosa,129348,38740,39517,1.0
1899,OK574287.1,28-SEP-2022,Phytophthora cinnamomi voucher CBS 144.22 mito...,"Li,M. and Lin,T.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39412,Phytophthora cinnamomi,4785,38409,39186,1.0
1900,OK574286.1,28-SEP-2022,Phytophthora plurivora voucher CBS124_093 mito...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,38039,Phytophthora plurivora,639000,37039,37816,1.0
1901,OK574285.1,28-SEP-2022,Phytophthora cactorum voucher cac_nanlinB mito...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGGCAACAAGATGGCTTTTTT...,38071,Phytophthora cactorum,29920,37101,37878,1.0
1902,OK574284.1,28-SEP-2022,Phytophthora cactorum voucher 262HNP mitochond...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGGCAACAAGATGGCTTTTTT...,38014,Phytophthora cactorum,29920,37042,37819,1.0
1903,OK555490.1,28-SEP-2022,Phytophthora cactorum voucher CH98PA11 mitocho...,"Li,M. and Lin,T.",ATGAATTTTCAAAATATAAATAAATGGGCAACAAGATGGCTTTTTT...,38016,Phytophthora cactorum,29920,37044,37821,1.0
5516,AY534144.1,26-JUL-2016,Saprolegnia ferax strain ATCC 36051 mitochondi...,"Grayburn,W.S., Hudspeth,D.S., Gane,M.K. and Hu...",ATGATACCTATTATTATAAATGGTGTAAAAATGCATGTAAAAAAAA...,46930,Saprolegnia ferax,4770,31826,32585,1.0
6733,PQ510212.1,24-DEC-2024,Phytophthora oleae isolate VK10A mitochondrion...,"Conti Taguali,S., Riolo,M., La Spada,F., Cacci...",ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,38191,Phytophthora oleae,2107226,37188,37965,1.0
8291,PP108243.1,24-JAN-2024,Phytophthora cinnamomi strain ZYM-1 mitochondr...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39307,Phytophthora cinnamomi,4785,38304,39081,1.0
8292,PP108242.1,24-JAN-2024,Phytophthora cinnamomi strain P2428 mitochondr...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39291,Phytophthora cinnamomi,4785,38288,39065,1.0
8293,PP108241.1,24-JAN-2024,Phytophthora cinnamomi strain MT20 mitochondri...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39298,Phytophthora cinnamomi,4785,38295,39072,1.0
8294,PP108240.1,24-JAN-2024,Phytophthora cinnamomi strain MT17 mitochondri...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39298,Phytophthora cinnamomi,4785,38295,39072,1.0
8295,PP108239.1,24-JAN-2024,Phytophthora cinnamomi strain MAFF_0235145 mit...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39298,Phytophthora cinnamomi,4785,38295,39072,1.0
8296,PP108238.1,24-JAN-2024,Phytophthora cinnamomi strain CT09CHAP1 mitoch...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39298,Phytophthora cinnamomi,4785,38295,39072,1.0
8297,PP108237.1,24-JAN-2024,Phytophthora cinnamomi strain CH95PHE1 mitocho...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39298,Phytophthora cinnamomi,4785,38295,39072,1.0
8298,PP108236.1,24-JAN-2024,Phytophthora cinnamomi strain CH00HYP6 mitocho...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39308,Phytophthora cinnamomi,4785,38305,39082,1.0
8299,PP108235.1,24-JAN-2024,Phytophthora cinnamomi strain ATCC_15401 mitoc...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39321,Phytophthora cinnamomi,4785,38318,39095,1.0
8300,PP108234.1,24-JAN-2024,Phytophthora cinnamomi strain ACCC_36284 mitoc...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39233,Phytophthora cinnamomi,4785,38230,39007,1.0
8301,PP108233.1,24-JAN-2024,Phytophthora cinnamomi strain 7574 mitochondri...,"Wang,H. and Li,M.",ATGAGTTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,39294,Phytophthora cinnamomi,4785,38291,39068,1.0

In [89]:
full_cox2_start['organism_name'].value_counts()

organism_name
Phytophthora nicotianae                  339
Phytophthora infestans                    90
Phytophthora agathidicida                 17
Phytophthora drechsleri                   16
Phytophthora cinnamomi                    14
                                        ...
Phytophthora cinnamomi var. cinnamomi      1
Phytophthora nicotianae CJ01A1             1
Phytophthora megasperma                    1
Phytophthora oleae                         1
Phytophthora insolita                      1
Name: count, Length: 82, dtype: int64

### Trim sequences to COX2 region

In [90]:
from Bio import SeqIO

In [91]:
def trim_seq(cox2_start: str, cox2_end: str, seq: str) -> str:
    start = int(str(cox2_start).lstrip('<'))
    end = int(str(cox2_end).lstrip('>'))
    assert(start < end)
    return seq[start:end]

In [92]:
filtered['sequence'] = filtered.apply(lambda row: trim_seq(row['cox2_start'], row['cox2_end'], row['sequence']), axis=1)
filtered

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,JF414552.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-274 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
1,JF414551.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-273 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
2,JF414550.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-272 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
3,JF414549.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-269 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
4,JF414548.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-268 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
...,...,...,...,...,...,...,...,...,...,...,...
8507,OR094655.1,28-AUG-2023,Peronospora belbahrii isolate p15-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,564,Peronospora belbahrii,622444,<0,>564,1.0
8508,OR094654.1,28-AUG-2023,Peronospora belbahrii isolate p14-1-1 cytochro...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,600,Peronospora belbahrii,622444,<0,>600,1.0
8509,OR094653.1,28-AUG-2023,Peronospora belbahrii isolate p13-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",CAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACC...,564,Peronospora belbahrii,622444,<0,>564,1.0
8510,OR094652.1,28-AUG-2023,Peronospora belbahrii isolate p12-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,601,Peronospora belbahrii,622444,<0,>601,1.0
8511,OR094651.1,28-AUG-2023,Peronospora belbahrii isolate p11-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",TTATGGAAGGTATTATTAACTTTCACCATGATTTAATGTTTTTTTT...,541,Peronospora belbahrii,622444,<0,>541,1.0

### Remove short (<200bp) sequences

In [93]:
trimmed = filtered[filtered['sequence'].str.len() >= 200]
trimmed

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,JF414552.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-274 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
1,JF414551.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-273 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
2,JF414550.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-272 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
3,JF414549.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-269 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
4,JF414548.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-268 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
...,...,...,...,...,...,...,...,...,...,...,...
8507,OR094655.1,28-AUG-2023,Peronospora belbahrii isolate p15-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,564,Peronospora belbahrii,622444,<0,>564,1.0
8508,OR094654.1,28-AUG-2023,Peronospora belbahrii isolate p14-1-1 cytochro...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,600,Peronospora belbahrii,622444,<0,>600,1.0
8509,OR094653.1,28-AUG-2023,Peronospora belbahrii isolate p13-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",CAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACC...,564,Peronospora belbahrii,622444,<0,>564,1.0
8510,OR094652.1,28-AUG-2023,Peronospora belbahrii isolate p12-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,601,Peronospora belbahrii,622444,<0,>601,1.0
8511,OR094651.1,28-AUG-2023,Peronospora belbahrii isolate p11-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",TTATGGAAGGTATTATTAACTTTCACCATGATTTAATGTTTTTTTT...,541,Peronospora belbahrii,622444,<0,>541,1.0

### Remove Sequences with unknown species (i.e. 'sp.')

In [94]:
trimmed = trimmed[~trimmed['organism_name'].str.contains('sp.', case=False, regex=False)]
trimmed

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,JF414552.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-274 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
1,JF414551.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-273 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
2,JF414550.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-272 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
3,JF414549.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-269 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
4,JF414548.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-268 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
...,...,...,...,...,...,...,...,...,...,...,...
8507,OR094655.1,28-AUG-2023,Peronospora belbahrii isolate p15-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,564,Peronospora belbahrii,622444,<0,>564,1.0
8508,OR094654.1,28-AUG-2023,Peronospora belbahrii isolate p14-1-1 cytochro...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,600,Peronospora belbahrii,622444,<0,>600,1.0
8509,OR094653.1,28-AUG-2023,Peronospora belbahrii isolate p13-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",CAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACC...,564,Peronospora belbahrii,622444,<0,>564,1.0
8510,OR094652.1,28-AUG-2023,Peronospora belbahrii isolate p12-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,601,Peronospora belbahrii,622444,<0,>601,1.0
8511,OR094651.1,28-AUG-2023,Peronospora belbahrii isolate p11-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",TTATGGAAGGTATTATTAACTTTCACCATGATTTAATGTTTTTTTT...,541,Peronospora belbahrii,622444,<0,>541,1.0

### Remove sequences from uncultured samples

In [95]:
trimmed[trimmed['organism_name'].str.contains('uncultured', case=False)]

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
4949,MG787100.1,10-DEC-2018,Uncultured Oomycota isolate Ect6Para cytochrom...,"Garvetto,A., Nezan,E., Badis,Y., Bilien,G., Ar...",GGTCGTACGTTGTGTTTATTTTTTTAATCAAACCGTTCATCCGCAA...,471,uncultured Oomycota,179533,<0,>471,1.0
4951,MF960909.1,04-DEC-2018,Uncultured Oomycota isolate Melo1Para cytochro...,"Garvetto,A., Nezan,E., Badis,Y., Bilien,G., Ar...",TTAACATAATGTTTTTTTTAATCGTGATTGTGGTCTTTACCTCGTG...,576,uncultured Oomycota,179533,<0,>576,1.0

In [96]:
trimmed = trimmed[~trimmed['organism_name'].str.contains('uncultured', case=False)]
trimmed

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,JF414552.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-274 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
1,JF414551.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-273 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
2,JF414550.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-272 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
3,JF414549.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-269 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
4,JF414548.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-268 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
...,...,...,...,...,...,...,...,...,...,...,...
8507,OR094655.1,28-AUG-2023,Peronospora belbahrii isolate p15-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,564,Peronospora belbahrii,622444,<0,>564,1.0
8508,OR094654.1,28-AUG-2023,Peronospora belbahrii isolate p14-1-1 cytochro...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,600,Peronospora belbahrii,622444,<0,>600,1.0
8509,OR094653.1,28-AUG-2023,Peronospora belbahrii isolate p13-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",CAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACC...,564,Peronospora belbahrii,622444,<0,>564,1.0
8510,OR094652.1,28-AUG-2023,Peronospora belbahrii isolate p12-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,601,Peronospora belbahrii,622444,<0,>601,1.0
8511,OR094651.1,28-AUG-2023,Peronospora belbahrii isolate p11-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",TTATGGAAGGTATTATTAACTTTCACCATGATTTAATGTTTTTTTT...,541,Peronospora belbahrii,622444,<0,>541,1.0

### Remove (nom. inval.) species

In [97]:
trimmed = trimmed[~trimmed['title'].str.contains('nom. inval.', case=False, regex=False)]
trimmed = trimmed[~trimmed['organism_name'].str.contains('nom. inval.', case=False, regex=False)]

In [98]:
trimmed.value_counts('tax_id')

tax_id
114742     342
4792       232
65357      197
143453     190
907947     167
          ...
1185511      1
1185512      1
1190596      1
1194341      1
1218935      1
Name: count, Length: 803, dtype: int64

In [99]:
trimmed[(trimmed['cox2_start'] != '<0') & (trimmed['sequence_length'] > 280) & (trimmed['sequence'].str.len() < 290)]

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
4018,KP264256.1,02-SEP-2016,Pythium irregulare voucher CH-R 26-P4 cytochro...,"Torres-Barragan,A., Whittington,H.D., Sun,J., ...",TTAAACATTAAAATCAAAATTAATTTTATTTTTTAACCATGTTAAA...,470,Globisporangium irregulare,36331,265,>470,-1.0
4022,KP264252.1,02-SEP-2016,Pythium irregulare voucher TNRroot302P1 cytoch...,"Torres-Barragan,A., Whittington,H.D., Sun,J., ...",TTAAACATTAAAATCAAAATTAATTTTATTTTTTAACCATGTTAAA...,550,Globisporangium irregulare,36331,262,>550,-1.0
4023,KP264251.1,02-SEP-2016,Pythium irregulare voucher TNRsoil29P1 cytochr...,"Torres-Barragan,A., Whittington,H.D., Sun,J., ...",TTAAACATTAAAATCAAAATTAATTTTATTTTTTAACCATGTTAAA...,489,Globisporangium irregulare,36331,271,>489,-1.0
4025,KP264249.1,02-SEP-2016,Pythium irregulare voucher TNRsoil10P1 cytochr...,"Torres-Barragan,A., Whittington,H.D., Sun,J., ...",TTAAACATTAAAATCAAAATTAATTTTATTTTTTAACCATGTTAAA...,480,Globisporangium irregulare,36331,262,>480,-1.0

In [100]:
def sanitize_org_name(org_name: str) -> str:
    org_name_arr = org_name.split(' ')
    to_remove = ['x', 'var.', 'var', 'aff.', 'aff', 'cf.', 'cf']
    for s in to_remove:
        try:
            org_name_arr.remove(s)
        except ValueError:
            pass
    return ' '.join(org_name_arr[:2])

In [101]:
trimmed['tax_id_sanitized'] = trimmed['tax_id']
trimmed['organism_name_sanitized'] = trimmed['organism_name'].apply(sanitize_org_name)
def fix_tax_id(row: pd.Series):
    if row['organism_name_sanitized'] == row['organism_name']:
        return row['tax_id']
    if row['organism_name_sanitized'] in trimmed['organism_name'].unique():
        new_tax_id = trimmed.loc[trimmed['organism_name'] == row['organism_name_sanitized']]['tax_id'].iloc[0]
        return new_tax_id
    return row['tax_id']

trimmed['tax_id_sanitized'] = trimmed.apply(fix_tax_id, axis=1)

In [102]:
species_groups = trimmed.groupby('organism_name_sanitized')
for _, species in species_groups:
    # accessions of refseq sequences contain an underscore
    # see https://www.ncbi.nlm.nih.gov/refseq/about/
    refseq = species[species['accession'].str.contains('_')]
    if not refseq.empty:
        non_refseq = species[~species['accession'].str.contains('_')]
        if not non_refseq.empty:
            trimmed.drop(trimmed[trimmed['accession'].isin(non_refseq['accession'])].index, inplace=True)
trimmed

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand,tax_id_sanitized,organism_name_sanitized
16,JF414536.1,12-DEC-2013,Pseudoperonospora celtidis isolate SMK17780 cy...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2162,Pseudoperonospora celtidis,291623,<0,726,1.0,291623,Pseudoperonospora celtidis
17,HM635956.1,12-DEC-2013,Pseudoperonospora cannabina isolate NY409 cyto...,"Runge,F., Choi,Y.-J. and Thines,M.",CAGCAACTCCCGTTATGGAAGGTATTATAAACTTTCATCATGATTT...,550,Pseudoperonospora cannabina,291622,<0,>550,1.0,291622,Pseudoperonospora cannabina
18,HM635955.1,12-DEC-2013,Pseudoperonospora cannabina isolate U181 cytoc...,"Runge,F., Choi,Y.-J. and Thines,M.",CAGCAACTCCCGTTATGGAAGGTATTATAAACTTTCATCATGATTT...,550,Pseudoperonospora cannabina,291622,<0,>550,1.0,291622,Pseudoperonospora cannabina
20,HM635953.1,12-DEC-2013,Pseudoperonospora urticae isolate PDD1 cytochr...,"Runge,F., Choi,Y.-J. and Thines,M.",CAGCAACTCCCGTTATGGAAGGTATTATTAACTTTCATCATGATTT...,550,Pseudoperonospora urticae,162119,<0,>550,1.0,162119,Pseudoperonospora urticae
21,HM635952.1,12-DEC-2013,Pseudoperonospora urticae isolate HOH1111 cyto...,"Runge,F., Choi,Y.-J. and Thines,M.",CGGCAACTCCCGTTATGGAAGGTATTATTAACTTTCATCATGATTT...,550,Pseudoperonospora urticae,162119,<0,>550,1.0,162119,Pseudoperonospora urticae
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8479,LC730894.1,31-AUG-2023,Aphanomyces iridis CK14D1 mitochondrial cox2 g...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTAGTTTTTTTTTTAG...,552,Aphanomyces iridis,601994,<0,>552,1.0,601994,Aphanomyces iridis
8480,LC730893.1,31-AUG-2023,Aphanomyces iridis CK12DI1 mitochondrial cox2 ...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTAGTTTTTTTTTTAG...,552,Aphanomyces iridis,601994,<0,>552,1.0,601994,Aphanomyces iridis
8482,LC730891.1,31-AUG-2023,Aphanomyces cochlioides MAFF 305845 mitochondr...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTAGTTTTTTTTTTAG...,552,Aphanomyces cochlioides,112091,<0,>552,1.0,112091,Aphanomyces cochlioides
8483,LC730890.1,31-AUG-2023,Aphanomyces cladogamus NBRC 103816 mitochondri...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTATTTTTTTTTTTAG...,552,Aphanomyces cladogamus,253176,<0,>552,1.0,253176,Aphanomyces cladogamus
8484,LC730888.1,31-AUG-2023,Aphanomyces cladogamus MAFF 242268 mitochondri...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTATTTTTTTTTTTAG...,552,Aphanomyces cladogamus,253176,<0,>552,1.0,253176,Aphanomyces cladogamus

In [103]:
trimmed.to_csv('data/cox2-db-filtered.csv', sep='\t', index=False)

In [104]:
with open('data/cox2-db-filtered.fa', 'w') as out:
    for index, row in trimmed.iterrows():
        print(f'>{row["accession"]}', file=out)
        print(row['sequence'], file=out)

#### cluster with vsearch

```bash
vsearch --cluster_fast data/cox2-db-filtered.fa -id 1.0 --strand both --msaout data/clust-msa.fa --clusterout_id --uc data/clust-results.tsv
```