In [1]:
import pandas as pd
from src import database

In [2]:
df = pd.read_csv('data/cox2_th/output/cox2_th-meta-clean.tsv', sep='\t')
df

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,pubmed,organism,...,cluster_id,species,domain,kingdom,phylum,class,order,family,genus,country
0,LC902567.1,21-NOV-2025,Salispina hoi ORB01 mitochondrial cox2 gene fo...,"Saliba,J.A.T. and Bennett,R.M.",NaN,619,Salispina hoi,3457200,NaN,Salispina hoi,...,0,Salispina hoi,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Rhipidiales,Salispinaceae,Salispina,Philippines
1,MW006635.1,23-NOV-2020,Globisporangium irregulare isolate UM1087 cyto...,"Callaghan,S.E.",NaN,621,Globisporangium irregulare,36331,NaN,Globisporangium irregulare,...,1,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium,Australia
2,LC902566.1,21-NOV-2025,Salispina lobata LU08 mitochondrial cox2 gene ...,"Saliba,J.A.T. and Bennett,R.M.",NaN,613,Salispina lobata,980198,NaN,Salispina lobata,...,2,Salispina lobata,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Rhipidiales,Salispinaceae,Salispina,Philippines
3,MT192208.1,12-MAR-2021,Globisporangium irregulare isolate GI19 cytoch...,"McGehee,C.S. and Raudales,R.E.",NaN,561,Globisporangium irregulare,36331,NaN,Globisporangium irregulare,...,3,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium,United States of America
4,PP444835.1,14-MAR-2024,Peronosclerospora maydis isolate Tabanan cytoc...,"Sugiarta,D., Susanta Wirya,G.A. and Agung Phab...",NaN,346,Peronosclerospora maydis,886949,NaN,Peronosclerospora maydis,...,4,Peronosclerospora maydis,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Peronosclerospora,Indonesia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1309,MK602204.1,29-APR-2020,Globisporangium irregulare isolate C14 cytochr...,"Ibanez,J.M., Obregon,V.G. and Favaro,M.A.",NaN,518,Globisporangium irregulare,36331,NaN,Globisporangium irregulare,...,1194,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium,Argentina
1310,MK602213.1,29-APR-2020,Globisporangium irregulare isolate C24 cytochr...,"Ibanez,J.M., Obregon,V.G. and Favaro,M.A.",NaN,518,Globisporangium irregulare,36331,NaN,Globisporangium irregulare,...,1195,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium,Argentina
1311,KP420744.1,14-JUN-2015,Anisolpidium ectocarpii isolate An_PM_76_6 cyt...,"Gachon,C.M.M. and Mueller,D.G.",NaN,451,Anisolpidium ectocarpii,1663100,NaN,Anisolpidium ectocarpii,...,1196,Anisolpidium ectocarpii,Eukaryota,Stramenopiles,Oomycota,NaN,Anisolpidiales,Anisolpidiaceae,Anisolpidium,NaN
1312,MZ562303.1,01-MAY-2022,Pythium dissotocum isolate NS9 cytochrome oxid...,"McGehee,C.S. and Raudales,R.E.",NaN,430,Pythium dissotocum,82936,NaN,Pythium dissotocum,...,1197,Pythium dissotocum,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Pythium,United States of America
1313,MF527263.1,29-MAY-2018,Albugo tropica voucher PC0723703 cytochrome c ...,"Roch,S., Choi,Y.-J. and Thines,M.",NaN,471,Albugo tropica,2203415,NaN,Albugo tropica,...,1198,Albugo tropica,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Albuginales,Albuginaceae,Albugo,NaN

In [ ]:
df['organism_name_sanitized'] = df['organism_name']
df['organism_name_sanitized'] = df['organism_name_sanitized'].apply(database.sanitize_org_name)
df.index = df['accession']
is_on_mask = df['organism_name'] != df['organism_name_sanitized']
non_on_seqs = df[~is_on_mask]
non_on_species = non_on_seqs['organism_name'].unique()
# ON species that don't have a non-ON species name
# e.g. Globisporangium aff. irregulare while there is no Globisporangium irregulare
on_native_mask = is_on_mask & ~df['organism_name_sanitized'].isin(non_on_species)
on_native = df[on_native_mask]
trimmed = df.filter([*non_on_seqs.index, *on_native.index], axis='index')
trimmed

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,pubmed,organism,...,cluster_id,species,domain,kingdom,phylum,class,order,family,genus,country
LC902567.1,LC902567.1,21-NOV-2025,Salispina hoi ORB01 mitochondrial cox2 gene fo...,"Saliba,J.A.T. and Bennett,R.M.",NaN,619,Salispina hoi,3457200,NaN,Salispina hoi,...,0,Salispina hoi,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Rhipidiales,Salispinaceae,Salispina,Philippines
MW006635.1,MW006635.1,23-NOV-2020,Globisporangium irregulare isolate UM1087 cyto...,"Callaghan,S.E.",NaN,621,Globisporangium irregulare,36331,NaN,Globisporangium irregulare,...,1,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium,Australia
LC902566.1,LC902566.1,21-NOV-2025,Salispina lobata LU08 mitochondrial cox2 gene ...,"Saliba,J.A.T. and Bennett,R.M.",NaN,613,Salispina lobata,980198,NaN,Salispina lobata,...,2,Salispina lobata,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Rhipidiales,Salispinaceae,Salispina,Philippines
MT192208.1,MT192208.1,12-MAR-2021,Globisporangium irregulare isolate GI19 cytoch...,"McGehee,C.S. and Raudales,R.E.",NaN,561,Globisporangium irregulare,36331,NaN,Globisporangium irregulare,...,3,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium,United States of America
PP444835.1,PP444835.1,14-MAR-2024,Peronosclerospora maydis isolate Tabanan cytoc...,"Sugiarta,D., Susanta Wirya,G.A. and Agung Phab...",NaN,346,Peronosclerospora maydis,886949,NaN,Peronosclerospora maydis,...,4,Peronosclerospora maydis,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Peronosclerospora,Indonesia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
JF771454.1,JF771454.1,25-JUL-2016,Phytophthora sp. hungarica cytochrome oxidase ...,"Martin,F. and Radmer,L.",NaN,944,Phytophthora taxon hungarica,437581,NaN,Phytophthora taxon hungarica,...,908,Phytophthora taxon hungarica,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,Hungary
KJ469058.1,KJ469058.1,23-APR-2014,Phytophthora taxon raspberry isolate P896 cyto...,"Martin,F.N., Blair,J.E. and Coffey,M.D.",NaN,684,Phytophthora taxon raspberry,554913,24603058.0,Phytophthora taxon raspberry,...,917,Phytophthora taxon raspberry,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,Australia
KY436070.1,KY436070.1,01-APR-2017,Phytophthora taxon walnut isolate MVAP06099248...,"Fichtner,E., Kallsen,C.E., Dhaouadi,S. and Blo...",NaN,580,Phytophthora taxon walnut,1194341,NaN,Phytophthora taxon walnut,...,920,Phytophthora taxon walnut,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,United States of America
LC754343.1,LC754343.1,03-OCT-2024,Aphanomyces cf. keratinophilus NBRC 103821 mit...,"Kageyama,K., Watanabe,H., Otsubo,K., Hieno,A. ...",NaN,552,Aphanomyces cf. keratinophilus,3028233,NaN,Aphanomyces cf. keratinophilus,...,952,Aphanomyces cf. keratinophilus,Eukaryota,Stramenopiles,Oomycota,Saprolegniomycetes,Saprolegniales,Verrucalvaceae,Aphanomyces,Japan
PQ219684.1,PQ219684.1,16-SEP-2024,Phytophthora taxon hungarica isolate PH-40 cyt...,"Drugmand,B., McBride,E., Babu,B., Sakalauskas,...",NaN,960,Phytophthora taxon hungarica,437581,NaN,Phytophthora taxon hungarica,...,1017,Phytophthora taxon hungarica,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,Canada

In [19]:
on_remaining = trimmed[trimmed['organism_name'] != trimmed['organism_name_sanitized']]
on_remaining

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,pubmed,organism,...,cluster_id,species,domain,kingdom,phylum,class,order,family,genus,country
MG701996.1,MG701996.1,31-MAR-2019,Phytophthora taxon juncus isolate SCVWD615 cyt...,"Bourret,T.B., Mehl,H.K., Swiecki,T.J., Bernhar...",NaN,2134,Phytophthora taxon juncus,2065309,NaN,Phytophthora taxon juncus,...,17,Phytophthora taxon juncus,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,United States of America
MT583668.1,MT583668.1,06-APR-2021,Phytophthora x vanyenensis isolate QD32 cytoch...,"Dang,Q.N., Pham,T.Q., Arentz,F., Hardy,G.E.S. ...",NaN,558,Phytophthora x vanyenensis,2822408,NaN,Phytophthora x vanyenensis,...,82,Phytophthora x vanyenensis,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,Viet Nam
OR549688.1,OR549688.1,05-MAR-2024,Phytophthora x lusitanica isolate BD518 cytoch...,"Jung,T., Milenkovic,I., Balci,Y., Janousek,J.,...",NaN,983,Phytophthora x lusitanica,3073792,NaN,Phytophthora x lusitanica,...,90,Phytophthora x lusitanica,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
OR549684.1,OR549684.1,05-MAR-2024,Phytophthora x australasiatica isolate VN1117 ...,"Jung,T., Milenkovic,I., Balci,Y., Janousek,J.,...",NaN,988,Phytophthora x australasiatica,3073791,NaN,Phytophthora x australasiatica,...,104,Phytophthora x australasiatica,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
OR549730.1,OR549730.1,05-MAR-2024,Phytophthora x vanyenensis isolate SU1616 cyto...,"Jung,T., Milenkovic,I., Balci,Y., Janousek,J.,...",NaN,987,Phytophthora x vanyenensis,2822408,NaN,Phytophthora x vanyenensis,...,105,Phytophthora x vanyenensis,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
OR549735.1,OR549735.1,05-MAR-2024,Phytophthora x vanyenensis isolate TJ1114 cyto...,"Jung,T., Milenkovic,I., Balci,Y., Janousek,J.,...",NaN,986,Phytophthora x vanyenensis,2822408,NaN,Phytophthora x vanyenensis,...,106,Phytophthora x vanyenensis,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
OR549733.1,OR549733.1,05-MAR-2024,Phytophthora x vanyenensis isolate SU1720 cyto...,"Jung,T., Milenkovic,I., Balci,Y., Janousek,J.,...",NaN,987,Phytophthora x vanyenensis,2822408,NaN,Phytophthora x vanyenensis,...,107,Phytophthora x vanyenensis,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
KX777249.1,KX777249.1,08-FEB-2017,Peronospora cf. ducometii isolate WA-1 cytochr...,"Econopouly,B., Derie,M.L., Jones,S.S. and du T...",NaN,602,Peronospora cf. ducometii,1945754,NaN,Peronospora cf. ducometii,...,191,Peronospora cf. ducometii,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Peronospora,United States of America
MF687310.1,MF687310.1,20-MAR-2018,Peronospora aff. claytoniae cytochrome c oxida...,"Bourret,T.B., Choudhury,R.A., Mehl,H.K., Blomq...",NaN,2117,Peronospora aff. claytoniae,2028483,29529094.0,Peronospora aff. claytoniae,...,282,Peronospora aff. claytoniae,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Peronospora,United States of America
OR549711.1,OR549711.1,05-MAR-2024,Phytophthora x taiwanensis isolate TW248 cytoc...,"Jung,T., Milenkovic,I., Balci,Y., Janousek,J.,...",NaN,977,Phytophthora x taiwanensis,3073794,NaN,Phytophthora x taiwanensis,...,300,Phytophthora x taiwanensis,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
HM534956.1,HM534956.1,25-JUL-2016,Phytophthora sp. PgChlamydo strain P16851 cyto...,"Zhang,Y.H. and Coffey,M.D.",NaN,975,Phytophthora taxon Pgchlamydo,479473,NaN,Phytophthora taxon Pgchlamydo,...,358,Phytophthora taxon Pgchlamydo,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
LC596060.1,LC596060.1,24-DEC-2024,Phytophthora x stagnum ATCC MYA-4926 mitochond...,"Hieno,A., Otsubo,K., Fukui,M., Uematsu,S., Sug...",NaN,920,Phytophthora x stagnum,1306403,NaN,Phytophthora x stagnum,...,358,Phytophthora x stagnum,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
KJ654184.1,KJ654184.1,12-MAR-2019,Bremia aff. lagoseridis GLM68027 isolate B2104...,"Choi,Y.J., Beakes,G., Glockling,S., Kruse,J., ...",NaN,539,Bremia aff. lagoseridis GLM68027,1484098,25728598.0,Bremia aff. lagoseridis GLM68027,...,417,Bremia aff. lagoseridis GLM68027,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Bremia,NaN
JF771550.1,JF771550.1,25-JUL-2016,Phytophthora taxon Pgchlamydo isolate P10669 c...,"Martin,F. and Radmer,L.",NaN,945,Phytophthora taxon Pgchlamydo,479473,NaN,Phytophthora taxon Pgchlamydo,...,537,Phytophthora taxon Pgchlamydo,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,New Zealand
NC_063813.1,NC_063813.1,14-APR-2023,TPA: Phytophthora x alni culture CBS:117376 mi...,"Winkworth,R.C., Neal,G., Ogas,R.A., Nelson,B.C...",NaN,45343,Phytophthora x alni,299392,35420669.0,Phytophthora x alni,...,601,Phytophthora x alni,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
NC_063814.1,NC_063814.1,12-APR-2023,TPA: Phytophthora cambivora culture CBS:114087...,"Winkworth,R.C., Neal,G., Ogas,R.A., Nelson,B.C...",NaN,51184,Phytophthora x cambivora,53983,35420669.0,Phytophthora x cambivora,...,602,Phytophthora x cambivora,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
LC596058.1,LC596058.1,24-DEC-2024,Phytophthora x heterohybrida CBS 141207 mitoch...,"Hieno,A., Otsubo,K., Fukui,M., Uematsu,S., Sug...",NaN,906,Phytophthora x heterohybrida,1861847,NaN,Phytophthora x heterohybrida,...,602,Phytophthora x heterohybrida,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
LC596059.1,LC596059.1,24-DEC-2024,Phytophthora x incrassata CBS 141209 mitochond...,"Hieno,A., Otsubo,K., Fukui,M., Uematsu,S., Sug...",NaN,906,Phytophthora x incrassata,1861858,NaN,Phytophthora x incrassata,...,602,Phytophthora x incrassata,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,NaN
HQ660434.1,HQ660434.1,25-JUL-2016,Aphanomyces cf. repetans strain CBS 126887 cyt...,"Liu,P.-W. and Chen,C.",NaN,550,Aphanomyces cf. repetans,942735,NaN,Aphanomyces cf. repetans,...,752,Aphanomyces cf. repetans,Eukaryota,Stramenopiles,Oomycota,Saprolegniomycetes,Saprolegniales,Verrucalvaceae,Aphanomyces,NaN
EU810387.1,EU810387.1,26-JUL-2016,Phytophthora sp. oaksoil/Poland cytochrome c o...,"Belbahri,L., Calmin,G. and Lefort,F.",NaN,568,Phytophthora taxon Oaksoil,544548,NaN,Phytophthora taxon Oaksoil,...,875,Phytophthora taxon Oaksoil,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,Poland
JF771454.1,JF771454.1,25-JUL-2016,Phytophthora sp. hungarica cytochrome oxidase ...,"Martin,F. and Radmer,L.",NaN,944,Phytophthora taxon hungarica,437581,NaN,Phytophthora taxon hungarica,...,908,Phytophthora taxon hungarica,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,Hungary
KJ469058.1,KJ469058.1,23-APR-2014,Phytophthora taxon raspberry isolate P896 cyto...,"Martin,F.N., Blair,J.E. and Coffey,M.D.",NaN,684,Phytophthora taxon raspberry,554913,24603058.0,Phytophthora taxon raspberry,...,917,Phytophthora taxon raspberry,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,Australia
KY436070.1,KY436070.1,01-APR-2017,Phytophthora taxon walnut isolate MVAP06099248...,"Fichtner,E., Kallsen,C.E., Dhaouadi,S. and Blo...",NaN,580,Phytophthora taxon walnut,1194341,NaN,Phytophthora taxon walnut,...,920,Phytophthora taxon walnut,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,United States of America
LC754343.1,LC754343.1,03-OCT-2024,Aphanomyces cf. keratinophilus NBRC 103821 mit...,"Kageyama,K., Watanabe,H., Otsubo,K., Hieno,A. ...",NaN,552,Aphanomyces cf. keratinophilus,3028233,NaN,Aphanomyces cf. keratinophilus,...,952,Aphanomyces cf. keratinophilus,Eukaryota,Stramenopiles,Oomycota,Saprolegniomycetes,Saprolegniales,Verrucalvaceae,Aphanomyces,Japan
PQ219684.1,PQ219684.1,16-SEP-2024,Phytophthora taxon hungarica isolate PH-40 cyt...,"Drugmand,B., McBride,E., Babu,B., Sakalauskas,...",NaN,960,Phytophthora taxon hungarica,437581,NaN,Phytophthora taxon hungarica,...,1017,Phytophthora taxon hungarica,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora,Canada

In [3]:
filtered = database.filter_data(df)
filtered

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand,organism_name_sanitized,tax_id_sanitized
16,JF414536.1,12-DEC-2013,Pseudoperonospora celtidis isolate SMK17780 cy...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2162,Pseudoperonospora celtidis,291623,<0,726,1.0,Pseudoperonospora celtidis,291623
17,HM635956.1,12-DEC-2013,Pseudoperonospora cannabina isolate NY409 cyto...,"Runge,F., Choi,Y.-J. and Thines,M.",CAGCAACTCCCGTTATGGAAGGTATTATAAACTTTCATCATGATTT...,550,Pseudoperonospora cannabina,291622,<0,>550,1.0,Pseudoperonospora cannabina,291622
18,HM635955.1,12-DEC-2013,Pseudoperonospora cannabina isolate U181 cytoc...,"Runge,F., Choi,Y.-J. and Thines,M.",CAGCAACTCCCGTTATGGAAGGTATTATAAACTTTCATCATGATTT...,550,Pseudoperonospora cannabina,291622,<0,>550,1.0,Pseudoperonospora cannabina,291622
20,HM635953.1,12-DEC-2013,Pseudoperonospora urticae isolate PDD1 cytochr...,"Runge,F., Choi,Y.-J. and Thines,M.",CAGCAACTCCCGTTATGGAAGGTATTATTAACTTTCATCATGATTT...,550,Pseudoperonospora urticae,162119,<0,>550,1.0,Pseudoperonospora urticae,162119
21,HM635952.1,12-DEC-2013,Pseudoperonospora urticae isolate HOH1111 cyto...,"Runge,F., Choi,Y.-J. and Thines,M.",CGGCAACTCCCGTTATGGAAGGTATTATTAACTTTCATCATGATTT...,550,Pseudoperonospora urticae,162119,<0,>550,1.0,Pseudoperonospora urticae,162119
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8479,LC730894.1,31-AUG-2023,Aphanomyces iridis CK14D1 mitochondrial cox2 g...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTAGTTTTTTTTTTAG...,552,Aphanomyces iridis,601994,<0,>552,1.0,Aphanomyces iridis,601994
8480,LC730893.1,31-AUG-2023,Aphanomyces iridis CK12DI1 mitochondrial cox2 ...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTAGTTTTTTTTTTAG...,552,Aphanomyces iridis,601994,<0,>552,1.0,Aphanomyces iridis,601994
8482,LC730891.1,31-AUG-2023,Aphanomyces cochlioides MAFF 305845 mitochondr...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTAGTTTTTTTTTTAG...,552,Aphanomyces cochlioides,112091,<0,>552,1.0,Aphanomyces cochlioides,112091
8483,LC730890.1,31-AUG-2023,Aphanomyces cladogamus NBRC 103816 mitochondri...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTATTTTTTTTTTTAG...,552,Aphanomyces cladogamus,253176,<0,>552,1.0,Aphanomyces cladogamus,253176
8484,LC730888.1,31-AUG-2023,Aphanomyces cladogamus MAFF 242268 mitochondri...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTATTTTTTTTTTTAG...,552,Aphanomyces cladogamus,253176,<0,>552,1.0,Aphanomyces cladogamus,253176